BeUbi\JobeetBundle\Entity\Category:
    type: entity
    repositoryClass: BeUbi\JobeetBundle\Repository\CategoryRepository
    table: category
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
            unique: true
        slug:
            type: string
            length: 255
            unique: true
    oneToMany:
        jobs:
            targetEntity: Job
            mappedBy: category
        category_affiliates:
            targetEntity: CategoryAffiliate
            mappedBy: category
    lifecycleCallbacks:
      prePersist: [ setSlugValue ]
      preUpdate: [ setSlugValue ]
