BeUbi\JobeetBundle\Entity\User:
    type: entity
    table: user
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        username:
            type: string
            length: 255
        password:
            type: string
            length: 255
    lifecycleCallbacks: {  }
